parameters:
  - name: azureServiceConnection
    type: string
    default: ''
  - name: siteEnvPrefixLocal
    type: string
    default: ''
  - name: siteFarmId
    type: string
    default: ''
  - name: siteId
    type: string
    default: ''
  - name: uniqueMod
    type: string
    default: ''
  - name: containerRegistry
    type: string
    default: ''
  - name: tag
    type: string
    default: ''
  - name: sourceBranchName
    type: string
    default: ''
  - name: imageRepository
    type: string
    default: ''

steps:
  - task: AzureWebAppContainer@1
    displayName: '-- Push latest container'
    inputs:
      azureSubscription: ${{parameters.azureServiceConnection}}
      appName: '${{parameters.siteEnvPrefixLocal}}-ctcms-ct${{parameters.siteId}}-app${{parameters.uniqueMod}}'
      resourceGroupName: '${{parameters.siteEnvPrefixLocal}}-ctcms-df${{parameters.siteFarmId}}-app-rg'
      containers: '${{parameters.containerRegistry}}/${{parameters.imageRepository}}:${{parameters.tag}}'
