trigger:
  - none

pool:
  vmImage: ubuntu-latest

name: $(Build.BuildId)

parameters:
  - name: tag
    type: string
    default: ''
  - name: uniqueMod
    type: string
    default: '1'
  - name: sites_1
    type: object
    default: {}
  - name: sites_2
    type: object
    default: {}
  - name: sites_3
    type: object
    default: {}
  - name: sites_4
    type: object
    default: {}
  - name: sites_5
    type: object
    default: {}

variables:
  sourceBranchName: 'master'
  imageRepository: 'build/trialcourt/master'
  containerRegistry: 'globalctcmscr.azurecr.io'
  location: 'West US 3'
  azureServiceConnection: 'PROD Resource Manager'
  siteEnvPrefix: 'prod'
  siteId1: ''
  siteName1: ''
  siteFarmId1: ''
  ResourceGroupName1: ''
  siteId2: ''
  siteName2: ''
  siteFarmId2: ''
  ResourceGroupName2: ''
  siteId3: ''
  siteName3: ''
  siteFarmId3: ''
  ResourceGroupName3: ''
  siteId4: ''
  siteName4: ''
  siteFarmId4: ''
  ResourceGroupName4: ''
  siteId5: ''
  siteName5: ''
  siteFarmId5: ''
  ResourceGroupName5: ''

jobs:
  - job: ProcessSites1
    displayName: Process sites 1/5
    steps:
      - ${{ each site in parameters.sites_1 }}:
        - script: |
            IFS='|'
            read -a siteInfo <<< "${{site}}"
            echo "CountyId: ${siteInfo[0]}"
            echo "CountyName : ${siteInfo[2]}"
            echo "FarmId : ${siteInfo[1]}"
            echo "##vso[task.setvariable variable=siteId1;]${siteInfo[2]}"
            echo "##vso[task.setvariable variable=siteFarmId1;]${siteInfo[1]}"
            echo "##vso[task.setvariable variable=siteName1;]${siteInfo[0]}"
            echo "##vso[task.setvariable variable=ResourceGroupName1;]-ctcms-df${siteInfo[1]}-app-rg"
          displayName: 'SITE: ${{ site }}'
        - template: /.devops/pipeline/_provision-app-service.yml
          parameters:
            azureServiceConnection: $(azureServiceConnection)
            siteEnvPrefixLocal: $(siteEnvPrefix)
            resourceGroupName: $(ResourceGroupName1)
            location: $(location)
            siteFarmId: $(siteFarmId1)
            siteId:  '$(siteEnvPrefix)$(siteId1)'
            siteName: $(siteName1)
            uniqueMod: ${{parameters.uniqueMod}}
            buildId: $(Build.BuildId)
        - template: /.devops/pipeline/_deploy-container.yml
          parameters:
            azureServiceConnection: $(azureServiceConnection)
            siteEnvPrefixLocal: $(siteEnvPrefix)
            siteId: '$(siteEnvPrefix)$(siteId)'
            uniqueMod: ${{parameters.uniqueMod}}
            siteFarmId: $(siteFarmId)
            containerRegistry: $(containerRegistry)
            sourceBranchName: $(sourceBranchName)
            tag: ${{parameters.tag}}
  - job: ProcessSites2
    displayName: Process sites 2/5
    steps:
      - ${{ each site in parameters.sites_2 }}:
          - script: |
              IFS='|'
              read -a siteInfo <<< "${{site}}"
              echo "CountyId: ${siteInfo[0]}"
              echo "CountyName : ${siteInfo[2]}"
              echo "FarmId : ${siteInfo[1]}"
              echo "##vso[task.setvariable variable=siteId2;]${siteInfo[2]}"
              echo "##vso[task.setvariable variable=siteFarmId2;]${siteInfo[1]}"
              echo "##vso[task.setvariable variable=siteName2;]${siteInfo[0]}"
              echo "##vso[task.setvariable variable=ResourceGroupName2;]-ctcms-df${siteInfo[1]}-app-rg"
            displayName: 'SITE: ${{ site }}'
          - template: /.devops/pipeline/_provision-app-service.yml
            parameters:
              azureServiceConnection: $(azureServiceConnection)
              siteEnvPrefixLocal: $(siteEnvPrefix)
              resourceGroupName: $(ResourceGroupName2)
              location: $(location)
              siteFarmId: $(siteFarmId2)
              siteId: '$(siteEnvPrefix)$(siteId2)'
              siteName: $(siteName2)
              uniqueMod: ${{parameters.uniqueMod}}
              buildId: $(Build.BuildId)
          - template: /.devops/pipeline/_deploy-container.yml
            parameters:
              azureServiceConnection: $(azureServiceConnection)
              siteEnvPrefixLocal: $(siteEnvPrefix)
              siteId: '$(siteEnvPrefix)$(siteId2)'
              uniqueMod: ${{parameters.uniqueMod}}
              siteFarmId: $(siteFarmId2)
              containerRegistry: $(containerRegistry)
              sourceBranchName: $(sourceBranchName)
              tag: ${{parameters.tag}}
  - job: ProcessSites3
    displayName: Process sites 3/5
    steps:
      - ${{ each site in parameters.sites_3 }}:
          - script: |
              IFS='|'
              read -a siteInfo <<< "${{site}}"
              echo "CountyId: ${siteInfo[0]}"
              echo "CountyName : ${siteInfo[2]}"
              echo "FarmId : ${siteInfo[1]}"
              echo "##vso[task.setvariable variable=siteId3;]${siteInfo[2]}"
              echo "##vso[task.setvariable variable=siteFarmId3;]${siteInfo[1]}"
              echo "##vso[task.setvariable variable=siteName3;]${siteInfo[0]}"
              echo "##vso[task.setvariable variable=ResourceGroupName3;]-ctcms-df${siteInfo[1]}-app-rg"
            displayName: 'SITE: ${{ site }}'
          - template: /.devops/pipeline/_provision-app-service.yml
            parameters:
              azureServiceConnection: $(azureServiceConnection)
              siteEnvPrefixLocal: $(siteEnvPrefix)
              resourceGroupName: $(ResourceGroupName3)
              location: $(location)
              siteFarmId: $(siteFarmId3)
              siteId: '$(siteEnvPrefix)$(siteId3)'
              siteName: $(siteName3)
              uniqueMod: ${{parameters.uniqueMod}}
              buildId: $(Build.BuildId)
          - template: /.devops/pipeline/_deploy-container.yml
            parameters:
              azureServiceConnection: $(azureServiceConnection)
              siteEnvPrefixLocal: $(siteEnvPrefix)
              siteId: '$(siteEnvPrefix)$(siteId3)'
              uniqueMod: ${{parameters.uniqueMod}}
              siteFarmId: $(siteFarmId3)
              containerRegistry: $(containerRegistry)
              sourceBranchName: $(sourceBranchName)
              tag: ${{parameters.tag}}
  - job: ProcessSites4
    displayName: Process sites 4/5
    steps:
      - ${{ each site in parameters.sites_4 }}:
          - script: |
              IFS='|'
              read -a siteInfo <<< "${{site}}"
              echo "CountyId: ${siteInfo[0]}"
              echo "CountyName : ${siteInfo[2]}"
              echo "FarmId : ${siteInfo[1]}"
              echo "##vso[task.setvariable variable=siteId4;]${siteInfo[2]}"
              echo "##vso[task.setvariable variable=siteFarmId4;]${siteInfo[1]}"
              echo "##vso[task.setvariable variable=siteName4;]${siteInfo[0]}"
              echo "##vso[task.setvariable variable=ResourceGroupName4;]-ctcms-df${siteInfo[1]}-app-rg"
            displayName: 'SITE: ${{ site }}'
          - template: /.devops/pipeline/_provision-app-service.yml
            parameters:
              azureServiceConnection: $(azureServiceConnection)
              siteEnvPrefixLocal: $(siteEnvPrefix)
              resourceGroupName: $(ResourceGroupName4)
              location: $(location)
              siteFarmId: $(siteFarmId4)
              siteId: '$(siteEnvPrefix)$(siteId4)'
              siteName: $(siteName4)
              uniqueMod: ${{parameters.uniqueMod}}
              buildId: $(Build.BuildId)
          - template: /.devops/pipeline/_deploy-container.yml
            parameters:
              azureServiceConnection: $(azureServiceConnection)
              siteEnvPrefixLocal: $(siteEnvPrefix)
              siteId: '$(siteEnvPrefix)$(siteId4)'
              uniqueMod: ${{parameters.uniqueMod}}
              siteFarmId: $(siteFarmId4)
              containerRegistry: $(containerRegistry)
              sourceBranchName: $(sourceBranchName)
              tag: ${{parameters.tag}}
  - job: ProcessSites5
    displayName: Process sites 5/5
    steps:
      - ${{ each site in parameters.sites_5 }}:
          - script: |
              IFS='|'
              read -a siteInfo <<< "${{site}}"
              echo "CountyId: ${siteInfo[0]}"
              echo "CountyName : ${siteInfo[2]}"
              echo "FarmId : ${siteInfo[1]}"
              echo "##vso[task.setvariable variable=siteId5;]${siteInfo[2]}"
              echo "##vso[task.setvariable variable=siteFarmId5;]${siteInfo[1]}"
              echo "##vso[task.setvariable variable=siteName5;]${siteInfo[0]}"
              echo "##vso[task.setvariable variable=ResourceGroupName5;]-ctcms-df${siteInfo[1]}-app-rg"
            displayName: 'SITE: ${{ site }}'
          - template: /.devops/pipeline/_provision-app-service.yml
            parameters:
              azureServiceConnection: $(azureServiceConnection)
              siteEnvPrefixLocal: $(siteEnvPrefix)
              resourceGroupName: $(ResourceGroupName5)
              location: $(location)
              siteFarmId: $(siteFarmId5)
              siteId: '$(siteEnvPrefix)$(siteId5)'
              siteName: $(siteName5)
              uniqueMod: ${{parameters.uniqueMod}}
              buildId: $(Build.BuildId)
          - template: /.devops/pipeline/_deploy-container.yml
            parameters:
              azureServiceConnection: $(azureServiceConnection)
              siteEnvPrefixLocal: $(siteEnvPrefix)
              siteId: '$(siteEnvPrefix)$(siteId5)'
              uniqueMod: ${{parameters.uniqueMod}}
              siteFarmId: $(siteFarmId5)
              containerRegistry: $(containerRegistry)
              sourceBranchName: $(sourceBranchName)
              tag: ${{parameters.tag}}
